; ===============================
; BRDID – SIP Trunk por IP (inbound) + host (outbound)
; ===============================

; --- AOR (para saída: domínio fornecido pela BRDID) ---
[brdid-aor]
type=aor
contact=sip:voz.sobreip.com.br
qualify_frequency=60

; --- ENDPOINT ---
[brdid-endpoint]
type=endpoint
transport=transport-udp
context=taxi-inbound
disallow=all
allow=alaw,ulaw

aors=brdid-aor

; NAT / mídia (mantém o Asterisk no meio do áudio)
direct_media=no
rtp_symmetric=yes
force_rport=yes
rewrite_contact=yes

; Identificação confiável do número (se o provedor manda)
trust_id_inbound=yes
send_pai=yes

; --- IDENTIFY (inbound por IP) ---
[brdid-identify]
type=identify
endpoint=brdid-endpoint
match=189.113.38.59
match=186.209.45.20
match=186.209.52.214
match=216.10.29.131
