; =====================================================
; AUTO-GERADO - NAO EDITAR MANUALMENTE
; Arquivo: /etc/asterisk/queues.generated.conf
; Gerado em: 2026-02-12 13:48:54
; =====================================================

[uber_ringall]
musicclass=default
strategy=ringall
timeout=20
retry=1
wrapuptime=0
maxlen=0
joinempty=no
leavewhenempty=yes
ringinuse=no
setinterfacevar=yes
setqueuevar=yes

member => PJSIP/20
member => PJSIP/21
member => PJSIP/22
member => PJSIP/23
member => PJSIP/24
member => PJSIP/25
member => PJSIP/26
member => PJSIP/27
member => PJSIP/28
member => PJSIP/34
member => PJSIP/35
member => PJSIP/36
member => PJSIP/37
member => PJSIP/38
member => PJSIP/71
