; ===============================
; FILA RUA (destino fallback)
; login obrigatório: sem members fixos
; ===============================

[rua]
musicclass=default
strategy=linear
;strategy=rrmemory
timeout=10
retry=1
wrapuptime=0
maxlen=0
joinempty=no
leavewhenempty=yes
reportholdtime=yes
membergosub=rua-member-handler,s,1
